Реализован базовый функционал программы
IzabellaPavlova/C_CPP_homework pull request #1
Opened 2021-10-13 06:24 UTC by IzabellaPavlova

2021-10-13 11:46 UTC, DPeshkoff requested changes
Привет!

Нужно немного исправить решение

2021-10-13 11:46 UTC, DPeshkoff commented on homework1/src/films.h
> +};
Можно сделать `typedef`

2021-10-13 11:46 UTC, DPeshkoff commented on homework1/src/main.c
> +        return 0;
Вроде выходим с ошибкой, а возвращаем 0, как будто все ок

2021-10-13 11:46 UTC, DPeshkoff commented on homework1/src/main.c
> +    scanf("%s", &need_genre);
[Пункт 8](https://park.vk.company/blog/topic/view/12227/)

2021-10-13 11:46 UTC, DPeshkoff commented on homework1/src/main.c
> +}
\n

2021-10-13 11:46 UTC, DPeshkoff commented on homework1/src/films.h
> +void deletion(struct all_films *all_films);
\n

2021-10-13 11:46 UTC, DPeshkoff commented on homework1/src/films.c
> +        return 0;
Можно для красоты добавить отступ

2021-10-13 11:46 UTC, DPeshkoff commented on homework1/src/films.c
> +        scanf("%s", &string);
[Пункт 8](https://park.vk.company/blog/topic/view/12227/)

2021-10-13 11:46 UTC, DPeshkoff commented on homework1/src/films.c
> +        scanf("%s", &string);
Аналогично, пункт 8

2021-10-18 15:50 UTC, Vinograduss reviewed
1) нет тестов
2) нет ci

2021-10-18 15:50 UTC, Vinograduss commented on homework1/src/films.c
> +        char string[MAX_STRING_SIZE];
плохое название для переменной

2021-10-18 15:50 UTC, Vinograduss commented on homework1/src/films.c
> +    for (size_t i = 0; i < all_films->size; ++i){
нет проверки входных указателей

2021-10-18 15:50 UTC, Vinograduss commented on tests/films_test.cpp
> +
тестов нет

2021-11-08 22:45 UTC, closed without merging